# Generated by Django 5.2.5 on 2025-09-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=51665, upload_to='post_files/'),
            preserve_default=False,
        ),
    ]
