# Generated by Django 5.2.5 on 2025-09-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_file_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eshterack',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='eshterack',
            name='ended_date',
        ),
        migrations.RemoveField(
            model_name='eshterack',
            name='user',
        ),
    ]
