# Generated by Django 5.2.5 on 2025-09-18 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_usereshterack'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereshterack',
            name='post',
            field=models.ForeignKey(default=4465, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usereshterack',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
